# Generated by Django 2.2 on 2020-08-11 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tins', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tins',
            options={'ordering': ['-id']},
        ),
    ]
